### ISSUE TITLE
association_proxy between GameObject and attributes breaks

### ISSUE THREAD

**Issue by Natureshadow** [Veripeditus/veripeditus-server#53]
The association_proxy to the attributes breaks, at least with Flask-Restless 1.0.0b2. Not sure whether this is related to the update or the definition of the proxy is broken.

**Comment by Natureshadow** [comment]
Contacted @jfinkels by e-mail.

There is a pull request in jfinkels/flask-restless#608 that might be worth testing.

**Comment by Natureshadow** [comment]
With https://github.com/jfinkels/flask-restless/pull/608 we at least get a different exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/views/base.py", line 444, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/views/resources.py", line 400, in get
    return self._get_resource(resource_id)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/views/resources.py", line 335, in _get_resource
    return self._get_resource_helper(resource)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/views/base.py", line 1549, in _get_resource_helper
    result = serializer.serialize(resource, only=only)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/serialization/serializers.py", line 493, in serialize
    resource = self._dump(instance, only=only)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/serialization/serializers.py", line 315, in _dump
    assoc_scalars = list(assoc_proxy_scalar_collections(model))
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/helpers.py", line 116, in assoc_proxy_scalar_collections
    and not isinstance(v.remote_attr.property, RelationshipProperty) \
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/ext/associationproxy.py", line 175, in remote_attr
    return getattr(self.target_class, self.value_attr)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py", line 754, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/ext/associationproxy.py", line 225, in target_class
    return self._get_property().mapper.class_
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/ext/associationproxy.py", line 214, in _get_property
    return (orm.class_mapper(self.owning_class).
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/base.py", line 425, in class_mapper
    "Class object expected, got '%r'." % (class_, ))
```

**Comment by Natureshadow** [comment]
@Creeparoo, if we cannot get this fixed, shall we go with a `self.attribute("foo", "bar")` API for now until we can fix it?

**Comment by Creeparoo** [comment]
Yes!

**Comment by Natureshadow** [comment]
Removing from milestone as this is a Flask-Restless bug. We could release the beta without the dictionary API.

**Comment by Natureshadow** [comment]
https://github.com/jfinkels/flask-restless/issues/641

**Comment by Natureshadow** [comment]
Obsoleted by #117.
