### ISSUE TITLE
Exception in update_position

### ISSUE THREAD

**Issue by Natureshadow** [Veripeditus/veripeditus-server#97]
```
127.0.0.1 - - [28/Feb/2017 13:30:22] "GET /api/v2/gameobject/2/update_position/50.71597494653639,7.051806449890137 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/veripeditus/server/rest.py", line 96, in _get_gameobject_method_result
    ret = method_impl(arg)
  File "/usr/local/lib/python3.5/dist-packages/veripeditus/framework/model.py", line 427, in update_position
    if loc.distance_to(self) < loc.max_distance:
AttributeError: 'Null' object has no attribute 'max_distance'
```

**Comment by Natureshadow** [comment]
```
127.0.0.1 - - [28/Feb/2017 13:36:16] "GET /api/v2/gameobject/2/update_position/50.71605986051501,7.0515865087509155 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/veripeditus/server/rest.py", line 96, in _get_gameobject_method_result
    ret = method_impl(arg)
  File "/usr/local/lib/python3.5/dist-packages/veripeditus/framework/model.py", line 427, in update_position
    if loc.distance_to(self) < loc.distance_max:
TypeError: unorderable types: float() < NoneType()
```

**Comment by Natureshadow** [comment]
```
  File "/usr/local/lib/python3.5/dist-packages/veripeditus/framework/model.py", line 427, in update_position
    if hasattr(loc, "distance_max") and loc.distance_to(self) < loc.distance_max:
TypeError: unorderable types: float() < NoneType()
```
